### ISSUE TITLE
Task configuration

### ISSUE THREAD

**Issue by Seekeer** [cmgt/ya-disk-publish#2]
How should I configurate Yandex.Disk Publish Task?

Say I want to upload file `VK.zip` from root.
Now I got following settings:
![image](https://user-images.githubusercontent.com/2019187/47957529-72f65680-dfc8-11e8-8728-1da04454054b.png)
But it discover no files: 
   2018-11-03T21:24:12.9376545Z found 0 files
   2018-11-03T21:24:12.9376774Z Not found files to publish

While `Publish Build Artifacts` task creates drop with that file:
![image](https://user-images.githubusercontent.com/2019187/47957534-95886f80-dfc8-11e8-9619-0ed2a71be69d.png)

**Comment by cmgt** [comment]
Hi, @Seekeer. `Publish Build Artifacts task` with Artifact publish location Azure Pipelines not place build content in $(system.defaultworkingdirectory). Drop location not have UNC file share path and placement in file container as '#/881619/WinService'.
I don,t use `Publish Build Artifacts task` for create build release. I use `Archive task` for create zip archive with binaries and `Yandex.Disk Publish task` for upload to Yandex.Disk.  
![default](https://user-images.githubusercontent.com/6242281/48057303-c6cd8f00-e1c4-11e8-86b0-00ea1640f6c3.png)  
![default](https://user-images.githubusercontent.com/6242281/48057369-f381a680-e1c4-11e8-8e61-4ef4b30249fe.png)

**Comment by Seekeer** [comment]
Well
Now I Have:
![image](https://user-images.githubusercontent.com/2019187/48080647-36607000-e1ff-11e8-9581-727537dc917a.png)
and
![image](https://user-images.githubusercontent.com/2019187/48080664-4415f580-e1ff-11e8-8809-29f612a33f58.png)

but still 0 files found by Y.disk task

but for publish artifact task:
![image](https://user-images.githubusercontent.com/2019187/48080686-55f79880-e1ff-11e8-8a4f-f4f5a269ae27.png)
everything is ok

**Comment by cmgt** [comment]
`Archive task` root folder should be absolute path, example  $(system.defaultworkingdirectory)\Test ....
`Yandex.Disk task` contains an extra backslash, should be $(build.artifactstagingdirectory)

Please, attache your build log file, I'll see build process

**Comment by Seekeer** [comment]
> Archive task root folder should be absolute path
It works the same way with absolute as without

> Yandex.Disk task contains an extra backslash, should be $(build.artifactstagingdirectory)
Yep, I was testing different cases...

Here is logs for settings with absolute path and without slash:

[5_Archive MSVK.txt](https://github.com/cmgt/ya-disk-publish/files/2556828/5_Archive.MSVK.txt)
[6_Yandex.Disk Publish.txt](https://github.com/cmgt/ya-disk-publish/files/2556829/6_Yandex.Disk.Publish.txt)
[7_Publish Artifact 1.93.$(Rev.r).$(BuildID).zip copy.txt](https://github.com/cmgt/ya-disk-publish/files/2556830/7_Publish.Artifact.1.93.Rev.r.BuildID.zip.copy.txt)

**Comment by cmgt** [comment]
very strange, the function of getting a list of target files does not find the files to upload. I will try to reproduce the problem and release the fix.

**Comment by cmgt** [comment]
@Seekeer, please update your task installation. Current version 0.5.10

**Comment by Seekeer** [comment]
Thanks a lot! That fixed everything.
